apiVersion: v1
kind: Service
metadata:
  name: travelmedia-api-gateway-loadbalancer
spec:
  type: LoadBalancer 
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: travelmedia-api-gateway
