apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelmedia-message-service
spec:
  selector:
    matchLabels:
      app: travelmedia-message-service
  replicas: 1
  template:
    metadata:
      labels:
        app: travelmedia-message-service
    spec:
      containers:
        - name: travelmedia-message-service
          image: darsandinesh/travelmedia-message-service:latest
          ports:
            - containerPort: 40043
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: travelmedia-secrets
                  key: MESSAGE_PORT
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: travelmedia-secrets
                  key: MESSAGE_DB_URI
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: travelmedia-secrets
                  key: RABBITMQ_URL
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: travelmedia-secrets
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: travelmedia-secrets
                  key: S3_SECRET_ACCESS_KEY
            - name: S3_BUCKETNAME
              valueFrom:
                secretKeyRef:
                  name: travelmedia-secrets
                  key: S3_BUCKETNAME
            - name: S3_BUCKET_REGION
              valueFrom:
                secretKeyRef:
                  name: travelmedia-secrets
                  key: S3_BUCKET_REGION

---

apiVersion: v1
kind: Service
metadata:
  name: travelmedia-message-service
spec:
  type: ClusterIP
  selector:
    app: travelmedia-message-service
  ports:
    - protocol: TCP
      port: 40043
      targetPort: 40043
  